---
- include: preparation.yml
- include: serviceprincipal.yml
- include: storageaccount.yml
- include: resourcegroup.yml
- include: nsg.yml

- name: "Display data for Kentik portal"
  debug:
    msg: [
      "Subscription ID: {{ kentik_az_sub }}",
      "Resource Group: {{ kentik_az_resourcegroupname }}",
      "Location: {{ location }}",
      "Storage Account Name: {{ kentik_az_storageaccount }}",
    ]
